# Generated by Django 5.0.3 on 2024-03-31 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='quintity',
            new_name='quantity',
        ),
    ]
