# Generated by Django 5.0.3 on 2024-04-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_quintity_basket_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
